# -*- coding: utf-8 -*-
"""Letsgrowmore_Task_4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YdMcvTxK0PuCbLj9ICXO171Yj9C4aQUJ
"""

import cv2

img= cv2.imread("Photo_.jpg")  #load the image

gray_img=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY) #convert image to grayscale

inverted_gray_img=255-gray_img #invert the  grayscale image

blurred_img=cv2.GaussianBlur(inverted_gray_img,(45,45),0) #Apply Guassian Blur

inverted_blurred_img=255-blurred_img #invert the blurred image

pencil_sketch_img=cv2.divide(gray_img,inverted_blurred_img,scale=256.0) #create the pencil sketch image

cv2.imwrite("Output_image.jpg",pencil_sketch_img) #save the pencil sketch image

from skimage import io

img= io.imread('Photo_.jpg') 
io.imshow(img)

from skimage import io

img1=io.imread('Output_image.jpg')
io.imshow(img1)